config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root to: "questions#index"

  resources :questions do
    resources :answers, shallow: true      
  end
 
 
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :body, :question_id, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    
    @answer = @question.answers.new(answer_params)
    if @answer.save
      flash[:notice] = 'Answer successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def show
    @answer = Answer.find(params[:id])
  end

  protected

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show]

  def index
    @questions = Question.all
  end

  def show 
    @answer = @question.answers.build
  end

  def new 
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)

      if @question.save
        flash[:notice] = 'Question successfully created.'
        redirect_to @question

      else
        render :new
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
-if answer.persisted?
    div id="answer_#{answer.id}"
      = answer.body

app/views/answers/_form.html.slim
= form_for [@question, @answer] do |f| 
  p= f.label :body
  = f.text_area :body
  p= f.submit 'Send'

app/views/layouts/application.html.slim
doctype html
html
  head   
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  body

    - if current_user.present?
      = link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      p= link_to 'Sign in', new_user_session_path
      p= link_to 'Sign up', new_user_registration_path

    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/questions/index.html.slim
- @questions.each do |question|
  br
    = link_to question.title, question
p = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Create'

app/views/questions/show.html.slim
h2.title
  = @question.title
  .body
  = @question.body 
p = link_to 'Answer', new_question_answer_path(@question)

.answers
  = render @question.answers
  
= render partial: 'answers/form', q: @question
  